<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testsuite" nsURI="http://http://www.eclipse.org/gemoc/event/testsuite" nsPrefix="testsuite">
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCases" upperBound="-1" eType="//TestCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storage" upperBound="-1" containment="true">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedTrace">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" upperBound="-1" containment="true">
      <eType xsi:type="ecore:EClass" href="event.ecore#//EventOccurrence"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSuiteReport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCaseReports" upperBound="-1" eType="//TestCaseReport" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCaseReport" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" eType="//TestCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCaseSuccess" eSuperTypes="//TestCaseReport"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestCaseFailure" eSuperTypes="//TestCaseReport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trace">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCaseError" eSuperTypes="//TestCaseReport"/>
</ecore:EPackage>
