/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.executionframework.behavioralinterface


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BehavioralInterfaceRuntimeModule extends AbstractBehavioralInterfaceRuntimeModule {
}
