/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.executionframework.behavioralinterface


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BehavioralInterfaceStandaloneSetup extends BehavioralInterfaceStandaloneSetupGenerated {

	def static void doSetup() {
		new BehavioralInterfaceStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
