@startuml
skinparam class {
	BackgroundColor White
	ArrowColor Black
	BorderColor Black
}

scale max 1024 width
scale max 800 height

package "Java Execution / Java Engine" as java_execution <<Node>> {
	class PlainK3ExecutionEngine #beige {
	}  
	
	class Launcher #beige {
	}  
}

package K3 <<Node>> {
	interface IStepManager
}

package "GEMOC Framework / Framework Commons" as framework_commons <<Node>> {
	interface IDisposable
	interface IExecutionEngine
}
package eclipse.debug {
	interface ILaunchConfigurationDelegate
	interface ILaunchShortcut
}

package "GEMOC Framework / Execution Framework" as execution_framework <<Node>> {
	abstract class AbstractSequentialExecutionEngine
	abstract class AbstractCommandBasedSequentialExecutionEngine	
	abstract class AbstractSequentialGemocLauncher
	abstract class AbstractGemocLauncher
}
package "Simulation and Model Animation" as simulation_model_animation <<Node>> {
	abstract class AbstractDSLLaunchConfigurationDelegate
	abstract class AbstractDSLLaunchConfigurationDelegateUI
	abstract class AbstractDSLLaunchConfigurationDelegateSiriusUI
}


IDisposable <|.. AbstractSequentialExecutionEngine 
IExecutionEngine <|.. AbstractSequentialExecutionEngine 
AbstractSequentialExecutionEngine <|-- AbstractCommandBasedSequentialExecutionEngine
AbstractCommandBasedSequentialExecutionEngine <|-- PlainK3ExecutionEngine
IStepManager <|.. PlainK3ExecutionEngine

ILaunchConfigurationDelegate <|.. AbstractDSLLaunchConfigurationDelegate
ILaunchShortcut <|.. AbstractDSLLaunchConfigurationDelegateUI
AbstractDSLLaunchConfigurationDelegate <|-- AbstractDSLLaunchConfigurationDelegateUI 
AbstractDSLLaunchConfigurationDelegateUI <|-- AbstractDSLLaunchConfigurationDelegateSiriusUI
AbstractDSLLaunchConfigurationDelegateSiriusUI <|-- AbstractGemocLauncher
AbstractGemocLauncher <|-- AbstractSequentialGemocLauncher
AbstractSequentialGemocLauncher <|-- Launcher

@enduml
