@startuml
skinparam class {
	BackgroundColor White
	ArrowColor Black
	BorderColor Black
}

scale max 1024 width
scale max 800 height

package java_execution <<Node>> {
	class PlainK3ExecutionEngine #beige {
	}  
	
	class Launcher #beige {
	}  
}

package K3 <<Node>> {
	interface IStepManager
}

interface IDisposable
interface IExecutionEngine
interface ILaunchConfigurationDelegate

abstract class AbstractSequentialExecutionEngine
abstract class AbstractCommandBasedSequentialExecutionEngine
abstract class AbstractDSLLaunchConfigurationDelegate
abstract class AbstractDSLLaunchConfigurationDelegateUI
abstract class AbstractDSLLaunchConfigurationDelegateSiriusUI
abstract class AbstractSequentialGemocLauncher

IDisposable <|.. AbstractSequentialExecutionEngine 
IExecutionEngine <|.. AbstractSequentialExecutionEngine 
AbstractSequentialExecutionEngine <|-- AbstractCommandBasedSequentialExecutionEngine
AbstractCommandBasedSequentialExecutionEngine <|-- PlainK3ExecutionEngine
IStepManager <|.. PlainK3ExecutionEngine

ILaunchConfigurationDelegate <|.. AbstractDSLLaunchConfigurationDelegate
AbstractDSLLaunchConfigurationDelegate <|-- AbstractDSLLaunchConfigurationDelegateUI 
AbstractDSLLaunchConfigurationDelegateUI <|-- AbstractDSLLaunchConfigurationDelegateSiriusUI
AbstractDSLLaunchConfigurationDelegateSiriusUI <|-- AbstractSequentialGemocLauncher
AbstractSequentialGemocLauncher <|-- Launcher

@enduml
