/*
 * generated by Xtext 2.24.0
 */
package org.eclipse.gemoc.executionframework.behavioralinterface.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.gemoc.executionframework.behavioralinterface.parser.antlr.internal.InternalBehavioralInterfaceParser;
import org.eclipse.gemoc.executionframework.behavioralinterface.services.BehavioralInterfaceGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BehavioralInterfaceParser extends AbstractAntlrParser {

	@Inject
	private BehavioralInterfaceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBehavioralInterfaceParser createParser(XtextTokenStream stream) {
		return new InternalBehavioralInterfaceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BehavioralInterface";
	}

	public BehavioralInterfaceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BehavioralInterfaceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
