/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.executionframework.behavioralinterface.ide


/**
 * Use this class to register ide components.
 */
class BehavioralInterfaceIdeModule extends AbstractBehavioralInterfaceIdeModule {
}
