/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterfaceFactory
 * @model kind="package"
 * @generated
 */
public interface BehavioralInterfacePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "behavioralInterface";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.eclipse.org/gemoc/xdsmlframework/behavioralinterface/BehavioralInterface";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "behavioralInterface";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BehavioralInterfacePackage eINSTANCE = org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl.init();

  /**
   * The meta object id for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfaceImpl <em>Behavioral Interface</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfaceImpl
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getBehavioralInterface()
   * @generated
   */
  int BEHAVIORAL_INTERFACE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIORAL_INTERFACE__NAME = 0;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIORAL_INTERFACE__EVENTS = 1;

  /**
   * The number of structural features of the '<em>Behavioral Interface</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIORAL_INTERFACE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventImpl
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getEvent()
   * @generated
   */
  int EVENT = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__PARAMS = 2;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventParameterImpl <em>Event Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventParameterImpl
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getEventParameter()
   * @generated
   */
  int EVENT_PARAMETER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_PARAMETER__TYPE = 1;

  /**
   * The feature id for the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_PARAMETER__MANY = 2;

  /**
   * The number of structural features of the '<em>Event Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_PARAMETER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType <em>Event Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getEventType()
   * @generated
   */
  int EVENT_TYPE = 3;


  /**
   * Returns the meta object for class '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterface <em>Behavioral Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Behavioral Interface</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterface
   * @generated
   */
  EClass getBehavioralInterface();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterface#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterface#getName()
   * @see #getBehavioralInterface()
   * @generated
   */
  EAttribute getBehavioralInterface_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterface#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterface#getEvents()
   * @see #getBehavioralInterface()
   * @generated
   */
  EReference getBehavioralInterface_Events();

  /**
   * Returns the meta object for class '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getType()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Type();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getParams()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Params();

  /**
   * Returns the meta object for class '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter <em>Event Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Parameter</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter
   * @generated
   */
  EClass getEventParameter();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter#getName()
   * @see #getEventParameter()
   * @generated
   */
  EAttribute getEventParameter_Name();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter#getType()
   * @see #getEventParameter()
   * @generated
   */
  EAttribute getEventParameter_Type();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter#isMany <em>Many</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Many</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter#isMany()
   * @see #getEventParameter()
   * @generated
   */
  EAttribute getEventParameter_Many();

  /**
   * Returns the meta object for enum '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Event Type</em>'.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType
   * @generated
   */
  EEnum getEventType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BehavioralInterfaceFactory getBehavioralInterfaceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfaceImpl <em>Behavioral Interface</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfaceImpl
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getBehavioralInterface()
     * @generated
     */
    EClass BEHAVIORAL_INTERFACE = eINSTANCE.getBehavioralInterface();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEHAVIORAL_INTERFACE__NAME = eINSTANCE.getBehavioralInterface_Name();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIORAL_INTERFACE__EVENTS = eINSTANCE.getBehavioralInterface_Events();

    /**
     * The meta object literal for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventImpl
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__TYPE = eINSTANCE.getEvent_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__PARAMS = eINSTANCE.getEvent_Params();

    /**
     * The meta object literal for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventParameterImpl <em>Event Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.EventParameterImpl
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getEventParameter()
     * @generated
     */
    EClass EVENT_PARAMETER = eINSTANCE.getEventParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_PARAMETER__NAME = eINSTANCE.getEventParameter_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_PARAMETER__TYPE = eINSTANCE.getEventParameter_Type();

    /**
     * The meta object literal for the '<em><b>Many</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_PARAMETER__MANY = eINSTANCE.getEventParameter_Many();

    /**
     * The meta object literal for the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType <em>Event Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType
     * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.impl.BehavioralInterfacePackageImpl#getEventType()
     * @generated
     */
    EEnum EVENT_TYPE = eINSTANCE.getEventType();

  }

} //BehavioralInterfacePackage
