/**
 * generated by Xtext 2.24.0
 */
package org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getType <em>Type</em>}</li>
 *   <li>{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType
   * @see #setType(EventType)
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getEvent_Type()
   * @model
   * @generated
   */
  EventType getType();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventType
   * @see #getType()
   * @generated
   */
  void setType(EventType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getEvent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.Event#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.EventParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.eclipse.gemoc.executionframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getEvent_Params()
   * @model containment="true"
   * @generated
   */
  EList<EventParameter> getParams();

} // Event
